import { useState, useEffect } from 'react';
import { Settings } from '../types';
import { DEFAULT_SETTINGS } from '../constants/settings';
import { API_ENDPOINTS } from '../constants/api';
import { TIMING } from '../constants/timing';

export function useSettings() {
  const [settings, setSettings] = useState<Settings>(DEFAULT_SETTINGS);
  const [isSaving, setIsSaving] = useState(false);
  const [saveStatus, setSaveStatus] = useState('');

  useEffect(() => {
    // Load initial settings
    fetch(API_ENDPOINTS.SETTINGS)
      .then(res => res.json())
      .then(data => {
        setSettings({
          ULTRABRAIN_MODEL: data.ULTRABRAIN_MODEL || DEFAULT_SETTINGS.ULTRABRAIN_MODEL,
          ULTRABRAIN_CONTEXT_OBSERVATIONS: data.ULTRABRAIN_CONTEXT_OBSERVATIONS || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_OBSERVATIONS,
          ULTRABRAIN_WORKER_PORT: data.ULTRABRAIN_WORKER_PORT || DEFAULT_SETTINGS.ULTRABRAIN_WORKER_PORT,
          ULTRABRAIN_WORKER_HOST: data.ULTRABRAIN_WORKER_HOST || DEFAULT_SETTINGS.ULTRABRAIN_WORKER_HOST,

          // AI Provider Configuration
          ULTRABRAIN_PROVIDER: data.ULTRABRAIN_PROVIDER || DEFAULT_SETTINGS.ULTRABRAIN_PROVIDER,
          ULTRABRAIN_GEMINI_API_KEY: data.ULTRABRAIN_GEMINI_API_KEY || DEFAULT_SETTINGS.ULTRABRAIN_GEMINI_API_KEY,
          ULTRABRAIN_GEMINI_MODEL: data.ULTRABRAIN_GEMINI_MODEL || DEFAULT_SETTINGS.ULTRABRAIN_GEMINI_MODEL,
          ULTRABRAIN_GEMINI_RATE_LIMITING_ENABLED: data.ULTRABRAIN_GEMINI_RATE_LIMITING_ENABLED || DEFAULT_SETTINGS.ULTRABRAIN_GEMINI_RATE_LIMITING_ENABLED,

          // OpenRouter Configuration
          ULTRABRAIN_OPENROUTER_API_KEY: data.ULTRABRAIN_OPENROUTER_API_KEY || DEFAULT_SETTINGS.ULTRABRAIN_OPENROUTER_API_KEY,
          ULTRABRAIN_OPENROUTER_MODEL: data.ULTRABRAIN_OPENROUTER_MODEL || DEFAULT_SETTINGS.ULTRABRAIN_OPENROUTER_MODEL,
          ULTRABRAIN_OPENROUTER_SITE_URL: data.ULTRABRAIN_OPENROUTER_SITE_URL || DEFAULT_SETTINGS.ULTRABRAIN_OPENROUTER_SITE_URL,
          ULTRABRAIN_OPENROUTER_APP_NAME: data.ULTRABRAIN_OPENROUTER_APP_NAME || DEFAULT_SETTINGS.ULTRABRAIN_OPENROUTER_APP_NAME,

          // Token Economics Display
          ULTRABRAIN_CONTEXT_SHOW_READ_TOKENS: data.ULTRABRAIN_CONTEXT_SHOW_READ_TOKENS || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_SHOW_READ_TOKENS,
          ULTRABRAIN_CONTEXT_SHOW_WORK_TOKENS: data.ULTRABRAIN_CONTEXT_SHOW_WORK_TOKENS || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_SHOW_WORK_TOKENS,
          ULTRABRAIN_CONTEXT_SHOW_SAVINGS_AMOUNT: data.ULTRABRAIN_CONTEXT_SHOW_SAVINGS_AMOUNT || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_SHOW_SAVINGS_AMOUNT,
          ULTRABRAIN_CONTEXT_SHOW_SAVINGS_PERCENT: data.ULTRABRAIN_CONTEXT_SHOW_SAVINGS_PERCENT || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_SHOW_SAVINGS_PERCENT,

          // Observation Filtering
          ULTRABRAIN_CONTEXT_OBSERVATION_TYPES: data.ULTRABRAIN_CONTEXT_OBSERVATION_TYPES || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_OBSERVATION_TYPES,
          ULTRABRAIN_CONTEXT_OBSERVATION_CONCEPTS: data.ULTRABRAIN_CONTEXT_OBSERVATION_CONCEPTS || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_OBSERVATION_CONCEPTS,

          // Display Configuration
          ULTRABRAIN_CONTEXT_FULL_COUNT: data.ULTRABRAIN_CONTEXT_FULL_COUNT || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_FULL_COUNT,
          ULTRABRAIN_CONTEXT_FULL_FIELD: data.ULTRABRAIN_CONTEXT_FULL_FIELD || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_FULL_FIELD,
          ULTRABRAIN_CONTEXT_SESSION_COUNT: data.ULTRABRAIN_CONTEXT_SESSION_COUNT || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_SESSION_COUNT,

          // Feature Toggles
          ULTRABRAIN_CONTEXT_SHOW_LAST_SUMMARY: data.ULTRABRAIN_CONTEXT_SHOW_LAST_SUMMARY || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_SHOW_LAST_SUMMARY,
          ULTRABRAIN_CONTEXT_SHOW_LAST_MESSAGE: data.ULTRABRAIN_CONTEXT_SHOW_LAST_MESSAGE || DEFAULT_SETTINGS.ULTRABRAIN_CONTEXT_SHOW_LAST_MESSAGE,
        });
      })
      .catch(error => {
        console.error('Failed to load settings:', error);
      });
  }, []);

  const saveSettings = async (newSettings: Settings) => {
    setIsSaving(true);
    setSaveStatus('Saving...');

    const response = await fetch(API_ENDPOINTS.SETTINGS, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(newSettings)
    });

    const result = await response.json();

    if (result.success) {
      setSettings(newSettings);
      setSaveStatus('✓ Saved');
      setTimeout(() => setSaveStatus(''), TIMING.SAVE_STATUS_DISPLAY_DURATION_MS);
    } else {
      setSaveStatus(`✗ Error: ${result.error}`);
    }

    setIsSaving(false);
  };

  return { settings, saveSettings, isSaving, saveStatus };
}
